let translationsData = {
    es: {
      title: 'Pagina Principal',
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro',
      contactBtn: 'Contactame',
      welcome: "Soy Alex Desarrollador Web",
      aboutMe: 'Acerca de mi',
      aboutTitle: "Hola",
      aboutContent: "Soy desarrollador web, estudio desde hace 1 año de manera autodidacta en el area Front End y Back end, me apasiona el diseño y la resolución de problemas con codigo.",
      downloadcv: 'Descargar CV',
      findMe: 'Encuéntrame en',
      skillsTitle: 'Habilidades',
      projectsTitle: 'Proyectos',
      servicesTitle: 'Servicios',
      webService: 'Blogs, Paginas Institucionales, Personales, Equipos de Deporte, los diseños se ajustan a las necesidades del cliente, cada pagina viene con un diseño adaptativo multiplataforma.',
      streamingService: 'Diseño de Web + Servidor de Streaming Multimedia - Radio, TV, sin necesidad de hosting, el servidor correra desde tu propia PC, contaras con una herramienta propia para realizar el manejo de tu Stream.',
      storeService: 'Obten mas clientes con tu tienda en internet, contaras con una pagina con diseño ajustado a tus necesidades, integración con servicios de pagos y chat, y soporte para iniciar el manejo de tu tienda.',
      ctaTitle: "¿Tenes un proyecto en mente que quieras realizar?",
      cta: "Hablemos",
      ctaForm: 'DEJAME UN MENSAJE',
      contactTitle: 'Hablemos',
      formName: 'Nombre',
      formEmail: 'Correo',
      formMsg: 'Mensaje',
      formSent: 'Enviar Mensaje',
      formNameValidate: 'Ingresa un nombre',
      formEmailValidate: 'Ingresa un correo',
      formMsgValidate: 'Escribi algo',
      formMsgSent: 'Mensaje Enviado',
      formMsgError: 'Error intente mas tarde',
      notFound: 'Esta pagina no existe.',
      wip: 'En Desarrollo'
    },
    en: {
      title: 'Home Page',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      contactBtn: 'Contact Me',
      welcome: "im Alex Web Developer",
      aboutMe: 'About me',
      aboutTitle: "Hello",
      aboutContent: "Im a web developer, i started learning self taught a year ago in the Front End and Back End Area, i like the design and solve problems with code.",
      downloadcv: 'Download CV',
      findMe: 'Find me on',
      skillsTitle: 'Skills',
      projectsTitle: 'Projects',
      servicesTitle: 'Services',
      webService: 'Blogs, Institucional Pages, Personal Pages, Sport Teams, the design is adapted to the client needs, every pages comes with a multiplatform adaptative design.',
      streamingService: 'Web Design + Streaming Multimedia Server - Radio, TV, without hosting, the server will run through your own PC, you will receive a self made Tools for manage the content of your Stream.',
      storeService: 'Get more clients with your store in internet, you will get a webpage with a custom design adapted to your needs, integration of payment services and chat, and support to get started with the management of your store',
      ctaTitle: "Do you have a project in mind?",
      cta: "Get in touch",
      ctaForm: 'LEAVE A MESSAGE',
      contactTitle: "Let's Talk",
      formName: 'Name',
      formEmail: 'Email',
      formMsg: 'Message',
      formSent: 'Sent Message',
      formNameValidate: 'Enter your name',
      formEmailValidate: 'Enter your email',
      formMsgValidate: 'Write something',
      formMsgSent: 'Message Sent',
      formMsgError: 'Error try later',
      notFound: 'This page doesnt exist.',
      wip: 'Developing'
    }
  };
  
  export default translationsData;