let translationsData = {
    es: {
      title: 'Pagina Principal',
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro',
      contactBtn: 'Contactame',
      welcome: "Soy Alex Desarrollador Web",
      aboutMe: 'Acerca de mi',
      aboutTitle: "Hola",
      aboutContent: "Soy desarrollador web, estudio desde hace 1 año de manera autodidacta en el area Front End y Back end, me apasiona el diseño y la resolución de problemas con codigo.",
      downloadcv: 'Descargar CV',
      findMe: 'Encuéntrame en',
      skillsTitle: 'Habilidades',
      projectsTitle: 'Proyectos',
      ctaTitle: "¿Tenes un proyecto en mente que quieras realizar?",
      cta: "Hablemos",
      ctaForm: 'DEJAME UN MENSAJE',
      contactTitle: 'Hablemos',
      formName: 'Nombre',
      formEmail: 'Correo',
      formMsg: 'Mensaje',
      formSent: 'Enviar Mensaje',
      formNameValidate: 'Ingresa un nombre',
      formEmailValidate: 'Ingresa un correo',
      formMsgValidate: 'Escribi algo',
      formMsgSent: 'Mensaje Enviado',
      formMsgError: 'Error intente mas tarde',
      notFound: 'Esta pagina no existe.',
      wip: 'En Desarrollo'
    },
    en: {
      title: 'Home Page',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      contactBtn: 'Contact Me',
      welcome: "im Alex Web Developer",
      aboutMe: 'About me',
      aboutTitle: "Hello",
      aboutContent: "Im a web developer, i started learning self taught a year ago in the Front End and Back End Area, i like the design and solve problems with code.",
      downloadcv: 'Download CV',
      findMe: 'Find me on',
      skillsTitle: 'Skills',
      projectsTitle: 'Projects',
      ctaTitle: "Do you have a project in mind?",
      cta: "Get in touch",
      ctaForm: 'LEAVE A MESSAGE',
      contactTitle: "Let's Talk",
      formName: 'Name',
      formEmail: 'Email',
      formMsg: 'Message',
      formSent: 'Sent Message',
      formNameValidate: 'Enter your name',
      formEmailValidate: 'Enter your email',
      formMsgValidate: 'Write something',
      formMsgSent: 'Message Sent',
      formMsgError: 'Error try later',
      notFound: 'This page doesnt exist.',
      wip: 'Developing'
    }
  };
  
  export default translationsData;